# Generated by Django 3.2.8 on 2021-10-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingservice',
            name='inbound_request_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
