# Generated by Django 3.2.8 on 2021-10-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_management', '0002_alter_messagingservice_inbound_request_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingservice',
            name='fallback_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
