# Generated by Django 3.2.8 on 2021-10-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_management', '0003_alter_messagingservice_fallback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingservice',
            name='scan_message_content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messagingservice',
            name='status_callback',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
