# Generated by Django 3.2.8 on 2021-11-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_management', '0005_auto_20211031_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2PBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('friendly_name', models.CharField(max_length=255, null=True)),
                ('policy_sid', models.CharField(max_length=255, null=True)),
                ('sid', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('status_callback', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('valid_until', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('friendly_name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sid', models.CharField(max_length=255, null=True)),
                ('policy_sid', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('status_callback', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a2p_profile_bundle_sid', models.CharField(max_length=64)),
                ('customer_profile_bundle_sid', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('failure_reason', models.CharField(max_length=255, null=True)),
                ('identity_status', models.CharField(max_length=64, null=True)),
                ('mock', models.BooleanField(default=False)),
                ('russell_3000', models.CharField(max_length=64, null=True)),
                ('sid', models.CharField(max_length=64)),
                ('skip_automatic_sec_vet', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=64)),
                ('tax_exempt_status', models.CharField(max_length=64, null=True)),
                ('tcr_id', models.CharField(max_length=64, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('a2p_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twilio_management.a2pbrand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
