# Generated by Django 3.2.8 on 2021-11-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_management', '0006_a2pbrand_brandregistration_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='status',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
