version: "3"

services:
    a2p_twilio_app:
        build: .
        container_name: 'a2p_twilio_capp'
        image: a2p_twilio_image
        command: make runserver
        stdin_open: true
        platform: linux/amd64
        tty: true
        volumes:
            - .:/code
        env_file:
            - .env
        ports:
            - "0.0.0.0:${APP_PORT}:${APP_PORT}"
        depends_on:
            - database
        extra_hosts:
            - "local.apploi.com:172.17.0.1"

    a2p_twilio_db:
        image: postgres
        container_name: 'a2p_twilio_cdb'
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - '.:/home'
        env_file:
            - .env

    # networks:
    #     db_shared:
    #         external:
    #         name: db_network